[project]
name = "mcp-sdk-functions-hosting-python"
version = "0.1.0"
description = "Sample FastMCP server hosted on Azure Functions"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.14.1",
    "azure-identity",
    "fastmcp"
]